customer/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns=[
    path('',views.Index,name='index'),
    path('signup/',views.Signup,name='signup'),
    path('login/',views.Login,name='login'),
    path('dashboard/',views.Dashboard,name='dashboard'),
    path('logout/',views.Logout,name='logout'),
    path('view_rest/',views.View_rest,name='view_rest'),
    path('menu/',views.menu,name='menu'),
    path('restaurants/<str:category>',views.restaurants,name='restaurants'),
    path('search/',views.search,name='search'),
    path('add_to_cart/<int:product_id>',views.add_to_cart,name='add_to_cart'),
    path('index_restaurant/<int:rest_id>',views.index_restaurant,name='index_restaurant'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_cart/<int:item_id>',views.remove_from_cart,name='remove_from_cart'),
    path('buy_now/',views.Buy_now,name='buy_now'),
    path('view_menu/',views.View_menu,name='view_menu'),
    path('add_to_cart2/<int:dish_id>',views.add_to_cart2,name='add_to_cart2')


]

eattasty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('restaurant/',include('restaurant.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
app_name='restaurant'
urlpatterns=[
    path('home/',views.Home,name='home'),
    path('admin_login/',views.Admin_login,name='admin_login'),
    path('add_restaurant/',views.Add_restaurant,name='add_restaurant'),
    path('view_restaurant/',views.View_restaurant,name='view_restaurant'),
    path('logout/',views.Logout,name='logout'),
    path('add_menu/',views.Add_menu,name='add_menu'),
    path('view_menu/',views.View_menu,name='view_menu'),
    path('update/<int:dish_id>',views.Update,name='update'),
    path('delete_dish/<int:dish_id>',views.Delete,name='delete_dish'),
    path('edit_restaurant<int:rest_id>',views.edit_restaurant,name='edit_restaurant'),
    path('view_order',views.view_order,name='view_order')

 ]

customer/models.py
from django.db import models
from restaurant.models import *

# Create your models here.
class Customer_registration(models.Model):
    name = models.TextField(max_length=100,null=True)
    email = models.EmailField(max_length=100,null=True)
    number = models.TextField(max_length=100,null=True)
    password = models.TextField(max_length=100,null=True)
    address = models.TextField(max_length=300,null=True)

class Cart(models.Model):
    dish = models.ForeignKey(Dishes,on_delete=models.CASCADE,null=True)
    restaurant = models.ForeignKey(Restaurant_reg,on_delete=models.CASCADE,null=True)
    customer = models.ForeignKey(Customer_registration,on_delete=models.CASCADE,null=True)
    quantity = models.PositiveBigIntegerField(default=1)
class Order(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Accepted', 'Accepted'),
        ('Rejected', 'Rejected')
    ]

    customer = models.ForeignKey(Customer_registration, on_delete=models.CASCADE,null=True)
    total_price = models.DecimalField(max_digits=10,decimal_places=2,null=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES, default='Pending',null=True)
    order_date =  models.DateTimeField(auto_now_add=True,null=True)
    dish_detail = models.ForeignKey(Cart,on_delete=models.CASCADE,null=True)
    restaurant_detail = models.ForeignKey(Restaurant_reg,on_delete=models.CASCADE,null=True)


# def __str__(self):
#     return self.customer.name
    
class OrderDetail(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,null=True)
    dish = models.ForeignKey(Dishes,on_delete=models.CASCADE,null=True)
    restaurant = models.ForeignKey(Restaurant_reg,on_delete=models.CASCADE,null=True)
    quantity = models.PositiveIntegerField()



 

customer/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . models import *
from restaurant.models import *
# Create your views here.
def Index(request):
    rest = Restaurant_reg.objects.all()
    context={
        "rest":rest
    }
    return render(request,'customer/index.html',context)
def Signup(request):
    if request.method=='POST':
        Name = request.POST['name']
        Email = request.POST['email']
        Number = request.POST['number']
        Address = request.POST['address']
        Password = request.POST['confirm_password']
        cust=Customer_registration(name=Name,email=Email,number=Number,address=Address,password=Password)
        cust.save()

    return render(request,'customer/signup.html')
def Login(request):
    if request.method=='POST':
        Email = request.POST['email']
        Password = request.POST['confirm_password']
        try:
            cust=Customer_registration.objects.get(email=Email,password=Password)
            request.session['customer']=cust.id
            
            return redirect('customer:dashboard')
        except Customer_registration.DoesNotExist:
            return render(request,'customer/login.html',{'msg':'invalid email or password'})
         
    return render(request,'customer/login.html')
def Dashboard(request):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
        cust = Customer_registration.objects.get(id=customer_id)
        rest = Restaurant_reg.objects.all()
        context={
            "cust":cust,
            "rest":rest
        }
        return render(request,'customer/dashboard.html',context)
    else:
        return render(request,'customer/index.html')
def Logout(request):
    if 'customer' in request.session:
        del request.session['customer']
        return redirect('customer:index')
    else:
        return render(request,'customer/index.html')
def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            dishes=Dishes.objects.filter(ddiscription__icontains=keyword)
            context={
                "dishes":dishes
            }
    return render(request,'customer/view_rest.html',context)
def View_rest(request):
    if 'customer' in request.session:
     dishes=Dishes.objects.all()
     
     context={
         "dishes":dishes
     }
     return render(request,'customer/view_rest.html',context)
    else:
        return render(request,'customer/login.html')
    
def menu(request):
    if 'customer' in request.session:
     dishes=Dishes.objects.all()
     context={
         "dishes":dishes
     }
     return render(request,'customer/view_rest.html',context)
    else:
       dishes=Dishes.objects.all()
       context={
         "dishes":dishes
     }
    return render(request,'customer/view_menu.html',context)
def View_menu(request):
    if 'customer' not in request.session:
     dishes=Dishes.objects.all()
     
     context={
         "dishes":dishes
     }
     return render(request,'customer/view_menu.html',context)
    else:
        return render(request,'customer/view_rest.html')
     
def add_to_cart(request,product_id):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
         
        cust = Customer_registration.objects.get(id=customer_id)
        if request.method=='POST':
            dish = Dishes.objects.get(id=product_id)
            rest = dish.drestaurant
            
            cart_item,created=Cart.objects.get_or_create(dish=dish,customer=cust,restaurant=rest)
            
            
            if not created:
                cart_item.quantity+=1
                cart_item.save()
        return redirect('customer:cart')
    else:
        return redirect('customer:login')





def restaurants(request,category):
    
    if category=="pizza":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }
    elif category=="dosa":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }
    elif category=="burger":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }
    elif category=="cake":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }
    elif category=="biriyani":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }
    elif category=="sandwich":
        dishes=Dishes.objects.filter(ddiscription__icontains=category)
        context={
                "dishes":dishes
            }

    return render(request,'customer/restaurants.html',context)
def index_restaurant(request,rest_id):
        resta =Restaurant_reg.objects.get(id=rest_id)
        dishes = Dishes.objects.filter(drestaurant=resta)
        rest = Restaurant_reg.objects.all()
   
        context = {
            "resta":resta,
            "dishes":dishes,
            "rest":rest

        }

    
        return render(request,'customer/index_restaurant.html',context)
def cart(request):
    
    if 'customer'in request.session:
        customer_id=request.session.get('customer')
        cust = Customer_registration.objects.get(id=customer_id)
        cart_items=Cart.objects.filter(customer=cust)
        
        

        total_price = sum(item.dish.dprice*item.quantity for item in cart_items)
        context={
            "total_price":total_price,
            "cart_items":cart_items,
            "cust":cust
        }
    return render(request,'customer/cart.html',context)
def remove_from_cart(request,item_id):
    if 'customer'in request.session:
        customer_id=request.session.get('customer')
        cust = Customer_registration.objects.get(id=customer_id)
        dish = Dishes.objects.get(id=item_id)
        cart_item = Cart.objects.get(dish=dish,customer=cust)
        cart_item.delete()
        return redirect('customer:cart')
def Buy_now(request):
     
    if 'customer'in request.session:
        customer_id=request.session.get('customer')
        cust = Customer_registration.objects.get(id=customer_id)
        cart_items = Cart.objects.filter(customer=cust)
 
        if not cart_items.exists():
            return redirect('customer:cart')
        restaurant = cart_items.first().restaurant
        total_price = sum(item.dish.dprice*item.quantity for item in cart_items)
        order = Order.objects.create(customer = cust,total_price = total_price,status = 'Pending',restaurant_detail=restaurant)
        for item in cart_items:
            OrderDetail.objects.create(order=order,dish=item.dish,quantity=item.quantity,restaurant=item.restaurant)
        cart_items.delete()
        order_details=OrderDetail.objects.filter(order=order)
        context={
            "cust":cust,
            "order":order,
            "total_price":total_price,
            "order_details":order_details
        }
         
        return render(request,'customer/payment.html',context)
    else:
        return render(request,'customer/index.html')
    

def add_to_cart2(request,dish_id):
    if 'customer' in request.session:
        customer_id=request.session.get('customer')
         
        cust = Customer_registration.objects.get(id=customer_id)
        if request.method=='POST':
            dish = Dishes.objects.get(id=dish_id)
            cart_item,created=Cart.objects.get_or_create(dish=dish,customer=cust)
            
            
            if not created:
                cart_item.quantity+=1
                cart_item.save()
        return redirect('customer:cart')
    else:
        return redirect('customer:login')


 

restaurant/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . models import *
from customer.models import *
# Create your views here.
def Home(request):
    return render(request,'restaurant/home.html')
def Admin_login(request):
    if request.method=='POST':
        REmail = request.POST['email']
        RPassword = request.POST['password']
        try:
            rest=Restaurant_reg.objects.get(restemail=REmail,restpassword=RPassword)
            request.session['restaurant']=rest.id
            return redirect('restaurant:view_restaurant')
        except Restaurant_reg.DoesNotExist:
            return render(request,'restaurant/admin_login.html',{'msg':'invalid email or password'})
    return render(request,'restaurant/admin_login.html')
def Add_restaurant(request):
    if request.method=='POST':
        Rname = request.POST['rname']
        Remail = request.POST['remail']
        Rnumber = request.POST['rnumber']
        Rpassword = request.POST['rconfirm_password']
        Raddress = request.POST['raddress']
        restu=Restaurant_reg(restname=Rname,restemail=Remail,restphone=Rnumber,restpassword=Rpassword,restaddress=Raddress)
        restu.save()
    return render(request,'restaurant/add_restaurant.html')
def View_restaurant(request):
     

    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        dishes = Dishes.objects.filter(drestaurant=rest)
        context={
            "dishes":dishes,
            "rest":rest
        }


    return render(request,'restaurant/view_restaurant.html',context)
def Logout(request):
    if 'restaurant' in request.session:
        del request.session['restaurant']
        return redirect('restaurant:admin_login')
    else:
        return render(request,'restaurant/home.html')
    
def Add_menu(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        if request.method=='POST':
            Dname = request.POST['dname']
            Ddescription = request.POST['ddescription']
            Dprice = request.POST['dprice']
            Dimage = request.FILES['dimage']
            Drest = rest
            dish=Dishes(dname=Dname,ddiscription=Ddescription,dprice=Dprice,dimage=Dimage,drestaurant=Drest)
            dish.save()

        return render(request,'restaurant/add_menu.html')
def View_menu(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        dishes = Dishes.objects.filter(drestaurant=rest)
        context={
            "dishes":dishes
        }
        
        return render(request,'restaurant/view_menu.html',context)
def Update(request,dish_id):
    dish_details=Dishes.objects.get(id=dish_id)
    if request.method=='POST':
            Dname = request.POST['dname']
            Ddescription = request.POST['ddescription']
            Dprice = request.POST['dprice']
            try:
              Dimage = request.FILES['dimage']
            except:
             Dimage=dish_details.dimage
           
            dish_details.dname=Dname
            dish_details.ddiscription=Ddescription
            dish_details.dprice=Dprice
            dish_details.dimage=Dimage
            dish_details.save()
    context={
        "dish_details":dish_details
    }


    return render(request,'restaurant/update.html',context)
def Delete(request,dish_id):
    Dishes.objects.get(id=dish_id).delete()
    return redirect('restaurant:view_restaurant')
def edit_restaurant(request,rest_id):
    rest_details=Restaurant_reg.objects.get(id=rest_id)
    if request.method=='POST':
            Rname = request.POST['rname']
            Rphone= request.POST['rnumber']
            Remail = request.POST['remail']
            Raddress = request.POST['raddress']
            Rconfirm = request.POST['rconfirm_password']
             
           
            rest_details.restname=Rname
            rest_details.restphone=Rphone
            rest_details.restemail=Remail
            rest_details.restaddress=Raddress
            rest_details.restpassword=Rconfirm
            rest_details.save()
    context={
        "rest_details":rest_details
    }


    return render(request,'restaurant/edit_restaurant.html',context)
def view_order(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        restaurant = Restaurant_reg.objects.get(id=restaurant_id)
        orders = Order.objects.all()
        order_details = OrderDetail.objects.filter(restaurant=restaurant)
        context={
            "orders":orders,
            "restaurant":restaurant,
            "order_details":order_details
            
             
        }
        
        # order_details = []

        # for order in orders:
        #     details = OrderDetail.objects.filter(order=order)
        #     order_details.append({
        #         'order':order,
        #         'details':details,
        #         'customer':order.customer

        #     })
        #     context={
        #         'restaurant':restaurant,
        #         'order_details':order_details
        #     }
        return render(request,'restaurant/view_order.html',context)
    else:
            return redirect('restaurant:login')

 

customer/templates/customer/confirm_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Order</h1>
    <h2></h2>
</body>
</html>

customer/templates/customer/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/tasty.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
  h2{
    margin-left: 80px;
  }
     </style>
</head>
<body>
{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search" action="{% url 'customer:search' %}" method="get">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search" name="keyword">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:signup' %}">Signup</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Restaurants
                    </a>
                    <ul class="dropdown-menu">
                      {% for rest in rest %}
                      <li><a class="dropdown-item" href="{% url 'customer:index_restaurant' rest.id %}">{{rest.restname}}</a></li>
                      {% endfor %}
                       <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'restaurant:add_restaurant' %}">Add your Restaurant</a></li>
                      <li><a class="dropdown-item" href="{% url 'restaurant:admin_login' %}">Restaurant login</a></li>

                    </ul>
                  </li>
                   
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:menu' %}">Menu</a>
                  </li>

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>
      {% endblock %}
      <div class="containerfluid">
        <div class="col">
            <div class="image_main">
                <div class="hungry">
                   <b> hungry?<br>
                    Order food from your nearby Restaurant</b>
                </div>
            </div>
        </div>
      </div>
      
      <div class="containerfluid">
        <div class="col-12">
          <br><br><h2>What are you craving for?</h2><br>
          <div class="container text-center">
            <div class="row">
             
              <div class="col"><div class="card" style="width: 18rem;">
                <a href="{% url 'customer:restaurants' 'pizza' %}"><img src="{% static 'images/pizza.jpg' %}" class="card-img-top" alt="pizza"></a>
                <div class="card-body">
                  <p class="card-text"><h3> Pizza</h3></p>
                </div>
              </div></div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'biriyani' %}"><img src="{% static 'images/biriyani.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> Biriyani</h3></p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'burger' %}"><img src="{% static 'images/burger2.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> Burger</h3></p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'cake' %}"><img src="{% static 'images/cake.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> cake</h3></p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'sandwich' %}"><img src="{% static 'images/sandwich2.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> Sandwich</h3></p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'dosa' %}"><img src="{% static 'images/dosa.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> Dosa</h3></p>
                  </div>
                </div>
              </div>
              
            </div>


        </div>
      </div>
       


      
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card text-center">
        <div class="card-header">
          eattasty@gmail.com
        </div>
        <div class="card-body">
          <h5 class="card-title">Eattasy</h5>
          <p class="card-text">East fort,Thrissur<br>
          eattasty@gmail.com<br>
        Phone- 1234567890<br></p>
         </div>
        <div class="card-footer text-body-secondary">
          contact us on mail for enqueries
        </div>
      </div>
    </div>
  </div>
</div>






    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
</body>
</html>

customer/templates/customer/index_restaurant.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
  
   
     </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search" action="{% url 'customer:search' %}" method="get">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search" name="keyword">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                   
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:signup' %}">Signup</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Restaurants
                    </a>
                    <ul class="dropdown-menu">
                      {% for rest in rest %}
                      <li><a class="dropdown-item" href="{% url 'customer:index_restaurant' rest.id %}">{{rest.restname}}</a></li>
                      {% endfor %}
                       <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'restaurant:add_restaurant' %}">Add your Restaurant</a></li>
                    </ul>
                  </li>
                   
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:menu' %}">Menu</a>
                  </li>

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>

       

      <div class="container-fluid">
        <div class="row">
            <div class="col">

                <div class="card text-center">
                     
                    <div class="card-body">
                      <h1 class="card-title">{{resta.restname}}</h1>
                      <p class="card-text">{{resta.restemail}}</p>
                      <p class="card-text">{{resta.restaddress}}<br>
                      {{resta.restphone}}
                      </p>
 

                     </div>
                     
                  </div>



            </div>
        </div>
      </div>
<br><br>
      <div class="container-fluid">
        <div class="row">
          {% for dish in dishes %}
               <div class="col-6">
                <div class="card" style="width: 25rem;">
                    <img src="{{dish.dimage.url}}" class="card-img-top" alt="..."  >
                    <div class="card-body">
                      <h5 class="card-title">{{dish.dname}}</h5>
                      <p class="card-text">{{dish.ddiscription}}<br>
                      <h6>Price: {{dish.dprice}}</h6> 
                      </p>
                      <form action="{% url 'customer:add_to_cart2' dish.id %}" method="post"> 
                        {% csrf_token %}
  
                      <button type="submit" class="btn btn-success">add to cart</button>
   
                    </form>
                    </div>
                  </div>
            </div>
            {% endfor %}
             </div>
      </div>




      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
  </body>
  </html>