customer/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns=[
    path('',views.Index,name='index'),
    path('signup/',views.Signup,name='signup'),
    path('login/',views.Login,name='login'),
    path('dashboard/',views.Dashboard,name='dashboard'),
    path('logout/',views.Logout,name='logout'),
    path('view_rest/',views.View_rest,name='view_rest'),
    path('menu/',views.menu,name='menu'),
    path('restaurants/<str:category>',views.restaurants,name='restaurants'),
    path('search/',views.search,name='search'),
    path('add_to_cart/<int:product_id>',views.add_to_cart,name='add_to_cart'),
    path('index_restaurant/<int:rest_id>',views.index_restaurant,name='index_restaurant'),
    path('cart/',views.cart,name='cart'),
    path('remove_from_cart/<int:item_id>',views.remove_from_cart,name='remove_from_cart'),
    path('buy_now/',views.Buy_now,name='buy_now'),
    path('view_menu/',views.View_menu,name='view_menu'),
    path('add_to_cart2/<int:dish_id>',views.add_to_cart2,name='add_to_cart2')


]

eattasty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customer.urls')),
    path('restaurant/',include('restaurant.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
app_name='restaurant'
urlpatterns=[
    path('home/',views.Home,name='home'),
    path('admin_login/',views.Admin_login,name='admin_login'),
    path('add_restaurant/',views.Add_restaurant,name='add_restaurant'),
    path('view_restaurant/',views.View_restaurant,name='view_restaurant'),
    path('logout/',views.Logout,name='logout'),
    path('add_menu/',views.Add_menu,name='add_menu'),
    path('view_menu/',views.View_menu,name='view_menu'),
    path('update/<int:dish_id>',views.Update,name='update'),
    path('delete_dish/<int:dish_id>',views.Delete,name='delete_dish'),
    path('edit_restaurant<int:rest_id>',views.edit_restaurant,name='edit_restaurant'),
    path('view_order',views.view_order,name='view_order')

 ]

restaurant/models.py
from django.db import models

# Create your models here.
class Restaurant_reg(models.Model):
    restname = models.TextField(max_length=100,null=True)
    restphone = models.TextField(max_length=100,null=True)
    restaddress = models.TextField(max_length=100,null=True)
    restemail = models.TextField(max_length=100,null=True)
    restpassword = models.TextField(max_length=100,null=True)

class Dishes(models.Model):
    dname = models.TextField(max_length=100,null=True)
    ddiscription = models.TextField(max_length=500,null=True)
    dprice = models.FloatField(null=True)
    dimage = models.ImageField(upload_to='dishes',null=True)
    drestaurant = models.ForeignKey(Restaurant_reg,on_delete=models.CASCADE,null=True)

restaurant/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . models import *
from customer.models import *
# Create your views here.
def Home(request):
    return render(request,'restaurant/home.html')
def Admin_login(request):
    if request.method=='POST':
        REmail = request.POST['email']
        RPassword = request.POST['password']
        try:
            rest=Restaurant_reg.objects.get(restemail=REmail,restpassword=RPassword)
            request.session['restaurant']=rest.id
            return redirect('restaurant:view_restaurant')
        except Restaurant_reg.DoesNotExist:
            return render(request,'restaurant/admin_login.html',{'msg':'invalid email or password'})
    return render(request,'restaurant/admin_login.html')
def Add_restaurant(request):
    if request.method=='POST':
        Rname = request.POST['rname']
        Remail = request.POST['remail']
        Rnumber = request.POST['rnumber']
        Rpassword = request.POST['rconfirm_password']
        Raddress = request.POST['raddress']
        restu=Restaurant_reg(restname=Rname,restemail=Remail,restphone=Rnumber,restpassword=Rpassword,restaddress=Raddress)
        restu.save()
    return render(request,'restaurant/add_restaurant.html')
def View_restaurant(request):
     

    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        dishes = Dishes.objects.filter(drestaurant=rest)
        context={
            "dishes":dishes,
            "rest":rest
        }


    return render(request,'restaurant/view_restaurant.html',context)
def Logout(request):
    if 'restaurant' in request.session:
        del request.session['restaurant']
        return redirect('restaurant:admin_login')
    else:
        return render(request,'restaurant/home.html')
    
def Add_menu(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        if request.method=='POST':
            Dname = request.POST['dname']
            Ddescription = request.POST['ddescription']
            Dprice = request.POST['dprice']
            Dimage = request.FILES['dimage']
            Drest = rest
            dish=Dishes(dname=Dname,ddiscription=Ddescription,dprice=Dprice,dimage=Dimage,drestaurant=Drest)
            dish.save()

        return render(request,'restaurant/add_menu.html')
def View_menu(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        rest = Restaurant_reg.objects.get(id=restaurant_id)
        dishes = Dishes.objects.filter(drestaurant=rest)
        context={
            "dishes":dishes
        }
        
        return render(request,'restaurant/view_menu.html',context)
def Update(request,dish_id):
    dish_details=Dishes.objects.get(id=dish_id)
    if request.method=='POST':
            Dname = request.POST['dname']
            Ddescription = request.POST['ddescription']
            Dprice = request.POST['dprice']
            try:
              Dimage = request.FILES['dimage']
            except:
             Dimage=dish_details.dimage
           
            dish_details.dname=Dname
            dish_details.ddiscription=Ddescription
            dish_details.dprice=Dprice
            dish_details.dimage=Dimage
            dish_details.save()
    context={
        "dish_details":dish_details
    }


    return render(request,'restaurant/update.html',context)
def Delete(request,dish_id):
    Dishes.objects.get(id=dish_id).delete()
    return redirect('restaurant:view_restaurant')
def edit_restaurant(request,rest_id):
    rest_details=Restaurant_reg.objects.get(id=rest_id)
    if request.method=='POST':
            Rname = request.POST['rname']
            Rphone= request.POST['rnumber']
            Remail = request.POST['remail']
            Raddress = request.POST['raddress']
            Rconfirm = request.POST['rconfirm_password']
             
           
            rest_details.restname=Rname
            rest_details.restphone=Rphone
            rest_details.restemail=Remail
            rest_details.restaddress=Raddress
            rest_details.restpassword=Rconfirm
            rest_details.save()
    context={
        "rest_details":rest_details
    }


    return render(request,'restaurant/edit_restaurant.html',context)
def view_order(request):
    if 'restaurant' in request.session:
        restaurant_id = request.session.get('restaurant')
        restaurant = Restaurant_reg.objects.get(id=restaurant_id)
        orders = Order.objects.all()
        order_details = OrderDetail.objects.filter(restaurant=restaurant)
        context={
            "orders":orders,
            "restaurant":restaurant,
            "order_details":order_details
            
             
        }
        
        # order_details = []

        # for order in orders:
        #     details = OrderDetail.objects.filter(order=order)
        #     order_details.append({
        #         'order':order,
        #         'details':details,
        #         'customer':order.customer

        #     })
        #     context={
        #         'restaurant':restaurant,
        #         'order_details':order_details
        #     }
        return render(request,'restaurant/view_order.html',context)
    else:
            return redirect('restaurant:login')

 

restaurant/templates/restaurant/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
     </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:admin_login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customer:index' %}">Order food</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:add_restaurant' %}">Add new restaurant</a>
                  </li>
                   

                   
                   

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>
      
      <div class="containerfluid">
        <div class="col">
            <div class="image_main">
                <div class="hungry">
                   <b> hungry?<br>
                    Order food from your nearby Restaurant</b>
                </div>
            </div>
        </div>
      </div>
      
      <div class="containerfluid">
        <div class="col-12">
          <br><br><h2>What are you craving for?</h2>
          <div class="container text-center">
            <div class="row">
             
              <div class="col"><div class="card" style="width: 18rem;">
                <a href="#"><img src="{% static 'images/pizza.jpg' %}" class="card-img-top" alt="pizza"></a>
                <div class="card-body">
                  <p class="card-text"><h3> Pizza</h3></p>
                </div>
              </div></div>
              <div class="col"><div class="card" style="width: 18rem;">
                <a href="{% url 'customer:restaurants' 'burger' %}"><img src="{% static 'images/burger2.jpg' %}" class="card-img-top" alt="pizza"></a>
                <div class="card-body">
                  <p class="card-text"><h3> Burger</h3></p>
                </div>
              </div></div>
              <div class="col"><div class="card" style="width: 18rem;">
                <a href="{% url 'customer:restaurants' 'sandwich' %}"><img src="{% static 'images/sandwich2.jpg' %}" class="card-img-top" alt="pizza"></a>
                <div class="card-body">
                  <p class="card-text"><h3> Sandwich</h3></p>
                </div>
              </div></div>
              <div class="col"><div class="card" style="width: 18rem;">
                <a href="{% url 'customer:restaurants' 'dosa' %}"><img src="{% static 'images/dosa.jpg' %}" class="card-img-top" alt="pizza"></a>
                <div class="card-body">
                  <p class="card-text"><h3> Dosa</h3></p>
                </div>
              </div></div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'cake' %}"><img src="{% static 'images/cake.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> cake</h3></p>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="card" style="width: 18rem;">
                  <a href="{% url 'customer:restaurants' 'biriyani' %}"><img src="{% static 'images/biriyani.jpg' %}" class="card-img-top" alt="pizza"></a>
                  <div class="card-body">
                    <p class="card-text"><h3> Biriyani</h3></p>
                  </div>
                </div>
              </div>
            </div>


        </div>
      </div>







    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
</body>
</html>

restaurant/templates/restaurant/view_menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
     </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:add_restaurant' %}">Add new restaurant</a>
                  </li>
                   

                   
                   

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>

       

      <div class="container-fluid">
        <div class="row">
            <div class="col">

                <div class="card text-center">
                     
                    <div class="card-body">
                      <h1 class="card-title">{{rest.restname}}</h1>
                      <p class="card-text">{{rest.restemail}}</p>
                      <p class="card-text">{{rest.restaddress}}<br>
                      {{rest.restphone}}
                      </p>

                      <a href="{% url 'restaurant:add_menu' %}" class="btn btn-success">Add menu</a>
                      <a href="{% url 'restaurant:view_restaurant' %}" class="btn btn-success">View menu</a>

                     </div>
                     
                  </div>



            </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row row-cols-1 row-cols-md-3 g-4">
          {% for dish in dishes %}
          <div class="col">
            <div class="card h-100">
              <img src="{{dish.dimage.url}}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              </div>
              <div class="card-footer">
                <small class="text-body-secondary">Last updated 3 mins ago</small>
              </div>
            </div>
          </div>
          {% endfor %}
      </div>




      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
  </body>
  </html>

restaurant/templates/restaurant/view_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
  h2{
    padding-left: 50px;
  }
  
   
     </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:add_restaurant' %}">Add new restaurant</a>
                  </li>
                   

                   
                   

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>

    <div class="container-fluid">
      <div class="col-12">
           <div class="row"></div>
                <br><h2>Order details</h2><br>
                
                  
                    {% for data in orders %}
                  <div class="card text-center mb-3" style="width: 60rem; border: 3px solid brown;">
                     <h5 class="card-title"><br>Order ID:{{data.id}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Customer Name : {{data.customer.name}}</h6>
                    <p class="card-text">
                      <strong>Address : </strong>{{data.customer.address}}<br>
                      <strong>Phone Number : </strong>{{data.customer.number}}<br>
                      <strong>Total Price : </strong> {{data.total_price}}<br>
                      <strong>Order Date : </strong> {{data.order_date}}<br><br>
                       <a href="#" class="btn btn-danger">Reject</a>
                      <a href="#" class="btn btn-success">Accept</a>
                    </p>
                    <h5>Ordered Dishes</h5>
                    {% for item in order_details %}
                    
                    <ul class="list-group">
                       
                        
                      <li class="list-group-item">
                         <strong>Dish Name : </strong>{{item.dish.dname}}<br>
                        <strong> Price : </strong>{{item.dish.dprice}}<br>
                        <strong> Quantity : </strong>{{item.quantity}}<br>
                        <strong>restaurant: </strong>{{item.restaurant.restname}}
                      </li>
                       
                    </ul>
                    {% endfor %}
                    </div>
                    </div>
               {% endfor %}


                     

        </div>
      







      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
  </body>
  </html>

restaurant/templates/restaurant/view_restaurant.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasty</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
     <style>
      .image_main{
    height: 300px;
    background-image: url("{% static 'images/first.png' %}");
    background-repeat: no-repeat;
    background-size: cover;
  
  }
  
   
     </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
           <div class="space_front"></div>
           
          <a class="navbar-brand" href="#">
            <img src="{% static 'images/nav_logo.jpg' %}" alt="tasty" width="170" height="">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <!-- <ul class="navbar-nav me-auto mb-2 mb-lg-0"> -->
              
                <div class="container-fluid">
                    <form class="d-flex" role="search">
                      <input class="form-control me-2 search_width" type="search" placeholder="Search for restaurant, cuisine or a dish" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
  
            <!-- </ul> -->
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text_styling">
                   
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:logout' %}">Logout</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:add_restaurant' %}">Add new restaurant</a>
                  </li>
                   

                   
                   

                   
                  <div class="space_btw"></div>
                  </ul>
                 
            </span>


          </div>
        </div>
      </nav>

       

      <div class="container-fluid">
        <div class="row">
            <div class="col">

                <div class="card text-center">
                     
                    <div class="card-body">
                      <h1 class="card-title">{{rest.restname}}</h1>
                      <p class="card-text">{{rest.restemail}}</p>
                      <p class="card-text">{{rest.restaddress}}<br>
                      {{rest.restphone}}
                      </p>

                      <a href="{% url 'restaurant:add_menu' %}" class="btn btn-success">Add menu</a>
                      <a href="{% url 'restaurant:edit_restaurant' rest.id %}" class="btn btn-success">Edit details</a>
                      <a href="{% url 'restaurant:view_order' %}" class="btn btn-success">View orders</a>


                     </div>
                     
                  </div>



            </div>
        </div>
      </div>
<br><br>
      <div class="container-fluid">
        <div class="row">
          {% for dish in dishes %}
               <div class="col-6">
                <div class="card" style="width: 25rem;">
                    <img src="{{dish.dimage.url}}" class="card-img-top" alt="..."  >
                    <div class="card-body">
                      <h5 class="card-title">{{dish.dname}}</h5>
                      <p class="card-text">{{dish.ddiscription}}<br>
                      <h6>Price: {{dish.dprice}}</h6> 
                      </p>
                      <a href="{% url 'restaurant:update' dish.id %}" class="btn btn-success">Update</a>
                      <a href="{% url 'restaurant:delete_dish' dish.id %}" class="btn btn-success">Delete</a>

                    </div>
                  </div>
            </div>
            {% endfor %}
             </div>
      </div>




      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>   
  </body>
  </html>